pjgibume/account/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('signup/',register_view,name="signup"),
]

pjgibume/pjgibume/urls.py
from django.contrib import admin
from django.urls import path,include
from gibumeapp.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name="home"),
    path('mypage', mypage, name = "mypage"),
    path('detail1/',detail1,name="detail1"),
    path('detail2/',detail2,name="detail2"),
    path('detail3/',detail3,name="detail3"),
    path('detail4/',detail4,name="detail4"),
    path('detail5/',detail5,name="detail5"),
    path('detail6/',detail6,name="detail6"),
    path('detail7/',detail7,name="detail7"),
    path('detail8/',detail8,name="detail8"),

    # product 페이지 
    path('product/<str:name>',product,name="product"),
    path('product/<str:name>/writecomment/', writecomment, name="writecomment"),
    
    # 선호도
    path('like/<str:name>/', like_post, name="like_post"),
    path('ok/<str:name>/', ok_post, name="ok_post"),
    path('dislike/<str:name>/', dislike_post, name="dislike_post"),
    # 댓글 삭제
    path('product/<str:name>/<str:id>/deletecomment', deletecomment, name="deletecomment"),
    # 댓글 좋아요
    path('product/<str:name>/<str:id>/yesUp', yesUp, name="yesUp"),
    # 댓글 싫어요
    path('product/<str:name>/<str:id>/noUp', noUp, name="noUp"),

    path('community/', community, name="community"),
    path('community/new/', community_new, name="community_new"),
    path('community/create/', create, name="create"),
    path('community_detail/<int:id>', community_detail, name='community_detail'),
    path('community_detail/<int:id>/community_delete', community_delete, name="community_delete"),
    path('community_detail/<int:id>/community_edit', community_edit, name="community_edit"),
    path('community_detail/<int:id>/community_update', community_update, name="community_update"),
    path('community_detail/<int:id>/save_post', save_post, name="save_post"),

    path('community_detail/<int:id>/writecomment/', writeCommunitycomment, name="writeCommunitycomment"), #
    path('community_detail/deletecomment/<int:blog_id>/<int:comment_id>',deleteCommunitycomment,name="deleteCommunitycomment"),

    path('community_detail/<int:blog_id>/<int:comment_id>/Up', Up, name="Up"),
    path('community_detail/<int:blog_id>/<int:comment_id>/Down', Down, name="Down"),

    path('perfume/', perfume, name = "perfume"),
    path('perfume/search', search, name="search"),
    path('education/',education,name="education"),
    path('educommonsense/',common,name="common"),
    path('eduquiz/',eduquiz,name="eduquiz"),
    path('account/', include('account.urls')),

    path('form/', form, name="form"),
    path('test/', test, name="test"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjgibume/gibumeapp/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.urls import reverse
from django.conf import settings

# 유저
class User(models.Model):
    id = models.CharField(max_length = 20,primary_key = True)
    password = models.CharField(max_length = 30)
    username = models.CharField(max_length=30)
    email = models.CharField(max_length= 30,null=True)
    gender = models.CharField(max_length = 30,null=True)
    age = models.IntegerField(null=True)

# 향수
class Perfume(models.Model):
    
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", default='', blank=True)
    ok_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="ok_posts", default='', blank=True)
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dislike_posts", default='', blank=True)
    
    brand = models.CharField(max_length=200, default = '') # 브랜드
    name = models.CharField(max_length=20, primary_key=True)  # 향수 이름
    perfume_img = models.CharField(max_length=100, default = '') # 향수 사진

    COLOR_CHOICES = (
        ('red', 'red'),
        ('ora', 'orange'),
        ('yel', 'yellow'),
        ('gre', 'green'),
        ('blu', 'blue'),
        ('pur', 'purple'),
        ('pin', 'pink'),
        ('whi', 'white'),
        ('bla', 'black'),
    )
    color = models.CharField(max_length=3, choices=COLOR_CHOICES) # 색 분류

    TIME_CHOICES = ( 
        ('per', '퍼퓸'),
        ('edp', '오드퍼퓸'),
        ('edt', '오드뜨왈렛'),
        ('edc', '오드콜로뉴'),
    )
    time = models.CharField(max_length=3, choices=TIME_CHOICES) # 지속 시간에 따른 향수 분류

   

    NOTE_CHOICES = (
        ('CI', 'Citrus fruits'),
        ('AR', 'Aromatics'),    
        ('FL', 'Floral'),
        ('GR', 'Green'),
        ('FR', 'Fruity'),
        ('SP', 'Spices'),
        ('WO', 'Wooded'),
        ('BA', 'Balsamic'),
    )

    note_group = MultiSelectField(choices=NOTE_CHOICES) # 노트 그룹( 검색 위한 분류 )
    
    top_note = models.CharField(max_length=400, default = '') # 탑 노트 세부 표기
    middle_note = models.CharField(max_length=400, default = '') # 미들 노트 세부 표기
    base_note = models.CharField(max_length=400, default = '') # 베이스 노트 세부 표기

    def __str__(self):
        return self.name

# 향수 댓글
class Comment(models.Model):
    name=models.ForeignKey(Perfume, on_delete=models.CASCADE,default='') 
    pub_date = models.DateTimeField(default='')
    content=models.TextField(default='')
    author = models.CharField(max_length=30, default='')
    # 
    yes_users=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="yes_posts", default='', blank=True)
    no_users=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="no_posts", default='', blank=True)

    #
    yes_count = models.PositiveIntegerField(default=0)
    no_count = models.PositiveIntegerField(default=0)

    def comment_summary(self):
        return self.content[:80]

# 커뮤니티
class Community(models.Model):
    writer = models.CharField(max_length=30, default='')
    title = models.CharField(max_length=200, null=True)
    date = models.DateTimeField(default='')
    body = models.TextField(null=True)
    image = models.ImageField(upload_to='gibumeapp/', null=True)
    save_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="save_posts", default='', blank=True)

class CommunityComment(models.Model):
    post=models.ForeignKey(Community, on_delete=models.CASCADE, default='', null=True)
    author_name=models.CharField(max_length=20, default='')
    comment_text=models.TextField(default='')
    created_at=models.DateTimeField(default='')

    # 
    up_users=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="up_posts", default='', blank=True)
    down_users=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="down_posts", default='', blank=True)

    #
    up_count = models.PositiveIntegerField(default=0)
    down_count = models.PositiveIntegerField(default=0)

pjgibume/gibumeapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Perfume
from .models import Comment
from .models import User
from .models import Community
from .models import CommunityComment
from django.utils import timezone
from django.db.models import Q
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def home(request):
    return render(request, 'home.html')

@login_required
def mypage(request):
    comments=Comment.objects.all()
    comment_list=comments.filter(author = request.user.username)
    comment_list=list(comment_list)

    community=Community.objects.all()
    community_list=community.filter(writer = request.user.username)
    community_list=list(community_list)
    save_post_list=community.filter(save_users = request.user)

    products=Perfume.objects.all()
    like_product_list=products.filter(like_users = request.user)
    ok_product_list=products.filter(ok_users = request.user)
    dislike_product_list=products.filter(dislike_users = request.user)

    com_comment=CommunityComment.objects.all()
    com_comment=com_comment.filter(author_name = request.user.username)
    com_comment=list(com_comment)
    return render(request, 'mypage.html', {'comment_list' : comment_list, 'community_list':community_list, 'save_post_list':save_post_list, 'like_product_list':like_product_list, 'ok_product_list':ok_product_list, 'dislike_product_list':dislike_product_list, 'com_comment':com_comment})

def detail1(request):
    products = Perfume.objects.all()
    products=products.filter(time='per')
    products=list(products)
    return render(request, 'detail1.html', {'products':products})

def detail2(request):
    products = Perfume.objects.all()
    products=products.filter(time='edc')
    products=list(products)
    return render(request, 'detail2.html', {'products':products})

def detail3(request):
    products = Perfume.objects.all()
    products=products.filter(color='red')
    products=list(products)
    return render(request, 'detail3.html', {'products':products})

def detail4(request):
    products = Perfume.objects.all()
    products=products.filter(color='blu')
    products=list(products)
    return render(request, 'detail4.html', {'products':products})

def detail5(request):
    products = Perfume.objects.all()
    products=products.filter(time='edt')
    products=list(products)
    return render(request, 'detail5.html', {'products':products})

def detail6(request):
    products = Perfume.objects.all()
    products=products.filter(time='edp')
    products=list(products)
    return render(request, 'detail6.html', {'products':products})

def detail7(request):
    products = Perfume.objects.all()
    products=products.filter(color='whi')
    products=list(products)
    return render(request, 'detail7.html', {'products':products})

def detail8(request):
    products = Perfume.objects.all()
    products=products.filter(color='ora')
    products=list(products)
    return render(request, 'detail8.html', {'products':products})

def product(request, name):
    product = Perfume.objects.get(pk=name)
    #comments=Comment.objects.filter(name=name)
    comments=Comment.objects.filter(name=name).order_by('-yes_count') #
    comment_list=list(comments)
    return render(request, 'product.html', {'product' : product, 'comment_list' : comment_list})

@login_required
# 댓글 작성
def writecomment(request, name):
    comment=Comment()
    comment.name = Perfume.objects.get(pk=name)
    comment.content=request.POST.get('content',False)
    comment.pub_date=timezone.datetime.now()
    comment.author=request.user
    comment.save()
    return redirect("product", name)

# 댓글 삭제
@login_required
def deletecomment(request, name, id):
    comment = get_object_or_404(Comment, pk=id)
    if comment.author != request.user.username:
        return redirect("product", name)
    else:
        comment.delete()
        return redirect("product", name)

def community(request):
    community=Community.objects.all()
    return render(request,'community.html', {'community':community})

def community_new(request):
    return render(request, 'community_new.html')

def create(request):
    community=Community()
    community.writer=request.user
    community.title=request.POST.get('title')
    community.body=request.POST.get('body')
    try:
        community.image=request.FILES['image']
    except:
        pass
    community.date=timezone.datetime.now()
    community.save()
    return redirect('/community_detail/'+str(community.id))

def community_detail(request, id):
    community_detail = get_object_or_404(Community, pk=id)
    comment = CommunityComment.objects.filter(post=id).order_by('-up_count') #
    return render(request, 'community_detail.html', {'community_detail':community_detail, 'comment':comment})

def community_edit(request, id):
    community=Community.objects.get(id=id)
    return render(request, 'community_edit.html', {'community':community})

def community_update(request, id):
    community = Community.objects.get(id = id)
    if community.writer != request.user.username: 
        return redirect('/community_detail/'+str(community.id))
    else:
        community.title = request.POST.get('title', False)
        community.body = request.POST.get('body', False)
        community.date=timezone.datetime.now()
        community.save() # 꼭 save!
        return redirect('/community_detail/'+str(community.id))

@login_required
def community_delete(request, id):
    community = get_object_or_404(Community, pk=id)
    if community.writer != request.user.username: #
        return redirect('/community/')
    else:
        community.delete()
        return redirect('/community/')

# save
def save_post(request, id):
    community = Community.objects.get(pk=id)
    if request.user.is_authenticated:
        if request.user in community.save_users.all():
            community.save_users.remove(request.user)
            community.save()
        else:
            community.save_users.add(request.user)
            community.save()
        return redirect('/community_detail/'+str(community.id))
    if not request.user.is_authenticated: 
        return redirect("login") 

def perfume(request):
    perfume_list = Perfume.objects.all()
    return render(request, 'perfume.html', {'perfume_list' : perfume_list})

def search(request):
    search_list = Perfume.objects.all()
    search_key = request.POST.get('search_key')
    if search_key:
        search_list = search_list.filter(Q(name__icontains=search_key) | Q(brand__icontains=search_key))
    return render(request, 'search.html', {'search_list' : search_list, 'search_key':search_key})

def education(request):
    return render(request, 'education.html')

def common(request):
    return render(request, 'educommonsense.html')

def eduquiz(request):
    return render(request, 'eduquize.html')

#like
# @login_required
def like_post(request, name):
    product = Perfume.objects.get(pk=name)
    if request.user.is_authenticated: #
        if request.user in product.like_users.all():
            product.like_users.remove(request.user)
            # product.like_count -= 1
            product.save()
        else:
            if request.user in product.ok_users.all():
                product.ok_users.remove(request.user)
                #product.ok_count -= 1
                product.like_users.add(request.user)
                #product.like_count += 1
                product.save()

            if request.user in product.dislike_users.all():
                product.dislike_users.remove(request.user)
                #product.dislike_count -= 1
                product.like_users.add(request.user)
                #product.like_count += 1
                product.save()
            else:
                product.like_users.add(request.user)
                #product.like_count += 1
                product.save()
        return redirect("product", name)

    if not request.user.is_authenticated: #
        return redirect("login") # 

#ok
# @login_required
def ok_post(request, name):
    product = Perfume.objects.get(pk=name)
    if request.user.is_authenticated: #
        if request.user in product.ok_users.all():
            product.ok_users.remove(request.user)
            # product.ok_count -= 1
            product.save()
        else:
            if request.user in product.like_users.all():
                product.like_users.remove(request.user)
                #product.like_count -= 1
                product.ok_users.add(request.user)
                #product.ok_count += 1
                product.save()

            if request.user in product.dislike_users.all():
                product.dislike_users.remove(request.user)
                #product.dislike_count -= 1
                product.ok_users.add(request.user)
                #product.ok_count += 1
                product.save()

            else:
                product.ok_users.add(request.user)
                #product.ok_count += 1
                product.save()
        return redirect("product", name)
    
    if not request.user.is_authenticated: #
        return redirect("login") # 

#dislike
# @login_required
def dislike_post(request, name):
    product = Perfume.objects.get(pk=name)
    if request.user.is_authenticated: #
        if request.user in product.dislike_users.all():
            product.dislike_users.remove(request.user)
            #product.dislike_count -= 1
            product.save()
        else:
            if request.user in product.like_users.all():
                product.like_users.remove(request.user)
                #product.like_count -= 1
                product.dislike_users.add(request.user)
                #product.dislike_count += 1
                product.save()

            if request.user in product.ok_users.all():
                product.ok_users.remove(request.user)

pjgibume/gibumeapp/templates/community.html
{% extends 'base.html' %} {%block content%}

<html>
    <head>
        {% load static %} {% block extrahead %}
        <link rel="stylesheet" href="{% static 'css/community.css' %}" />
        <title>COMMUNITY</title>
        {% endblock %}
    </head>

    <body>
        <div class="commnunityHeaderWrapper">
            <p class="maintitle">COMMUNITY</p>
        </div>
        <div class="commnuityBarWrapper">
            <div class="commnunityNewItem">
                <span>
                    <a href="{%url 'community_new' %}"
                        >향수 추천 포스팅 하러가기</a
                    >
                </span>
            </div>
        </div>
        <div class="contentsWrapper">
            <div class="postWrapper">
                <a href="{%url 'community_new' %}">
                    <div class="create">
                        <span>+</span>
                    </div>
                </a>
            </div>
            {% for post in community %}
            <a href="{%url 'community_detail' post.id%}">
                <div class="postWrapper">
                    <div class="postImg">
                        {% if post.image %}
                        <img src="{{post.image.url}}" alt="" />
                        {% endif %}
                    </div>
                    <div class="postContentWrapper">
                        <div class="uesrName">
                            <span> {{post.title}} </span>
                        </div>
                        <div class="data">
                            <span>{{post.date}}</span>
                        </div>
                        <div class="desc">
                            <span></span>
                        </div>
                    </div>
                </div>
            </a>
            {%endfor%}
        </div>
    </body>
    {% endblock%}
</html>

pjgibume/gibumeapp/templates/community_edit.html
<h1>글쓰기 페이지 입니다</h1>

<form action=" {%url 'community_update' community.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4>제목: </h4>
    <input type="text" name="title" value="{{community.title}}">
    <br>
    <br>
    <h4>본문: </h4>
    <textarea cols=40 rows=10 name="body">{{community.body}}</textarea>
    <br>
    <br>
    <h4>이미지: </h4>
    <input type="file" name='image' value={{community.image}}>
    <input class="btn btn-dark" type="submit" value="수정하기">
</form>

pjgibume/gibumeapp/templates/community_new.html
<h1>글쓰기 페이지 입니다</h1>

<form action="{%url 'create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4>제목: </h4>
    <input type="text" name="title">
    <br>
    <br>
    <h4>본문: </h4>
    <textarea cols=40 rows=10 name="body"></textarea>
    <br>
    <br>
    <h4>이미지: </h4>
    <input type="file" name='image'>
    <input class="btn btn-dark" type="submit" value="제출하기">
</form>

pjgibume/gibumeapp/templates/mypage.html
{% extends 'base.html' %} {%block content%}

<head>
  {% load static %} {% block extrahead %}

  <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
  
  {% endblock %}

<body>
  <div class="title">
    <p class="maintitle">MYPAGE</p>
    <a href = "#main">
      <div class="arrow">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </a>
  </div>
  <div class = "top" id = "main" style = "width:100%; height:40px; background-color:#282828;"></div>
  <div class="detail_1">
    <div class="detail_2">
      <div class="info1">
        <p class="subtitle">MY INFO</p1>
          <hr class = "line">
          <div class="profs">
            <div class="prof1"><img class="Img" src="../static/img/call.jpg" alt="" /></div>
            <div class="prof2">

              <p class="infodetail">닉네임 : {{user.nickname}}</p>
              <p class="infodetail">이메일 : {{user.email}}</p>
              <p class="infodetail">기타정보 : ({{user.gender}}) {{user.age}}세</p>
            </div>
          </div>
      </div>
      <br>
      <div class="info3">
        <p class="subtitle">PERFUME REVIEW</p1>
          <hr class = "line">
          <div class = "review">
          <div class="like">

            <div class="tabset">
              <!-- Tab 1 -->
              <input type="radio" name="tabset" id="tab1" aria-controls="like" checked>
              <label for="tab1">LIKE</label>
              <!-- Tab 2 -->
              <input type="radio" name="tabset" id="tab2" aria-controls="ok">
              <label for="tab2">OK</label>
              <!-- Tab 3 -->
              <input type="radio" name="tabset" id="tab3" aria-controls="dislike">
              <label for="tab3">DISLIKE</label>
              
              <div class="tab-panels">
                <section id="like" class="tab-panel">
                  <div class="perfume_list">
                    {%for product in like_product_list%}
                    <a href="{%url 'product' product.name%}">
                    <div class = "perfume">
                      <figure class = "perfume_thumb">
                        <img src="{% get_static_prefix %}img/{{product.perfume_img}}.jpg" class="perfume_img">
                        <figcaption class="perfume_caption">
                          <p class = "perfume_brand">[{{product.brand}}]</p>
                          <p class = "perfume_name">{{product.name}}</p>
                            <div class = "perfume_info">
                              <hr class = "h1">
                              <p class = "perfume_time" style = "padding-top:10px; padding-bottom:5px;">{{product.get_time_display}}</p>
                              <hr class = "h2">
                              <p class = "perfume_note" style = "padding-top:5px; padding-bottom:3px; width:95%;">{{product.get_note_group_display}}</p>
                            </div>
                        </figcaption>
                      </figure>
                    </div>
                    </a>
                    {% endfor %}
                    
                  </div>
                </section>
                <section id="ok" class="tab-panel">
                  <div class="perfume_list">
                    {%for product in ok_product_list%}
                    <a href="{%url 'product' product.name%}"> 
                      <div class = "perfume">
                        <figure class = "perfume_thumb">
                          <img src="{% get_static_prefix %}img/{{product.perfume_img}}.jpg" class="perfume_img">
                          <figcaption class="perfume_caption">
                            <p class = "perfume_brand">[{{product.brand}}]</p>
                            <p class = "perfume_name">{{product.name}}</p>
                              <div class = "perfume_info">
                                <hr class = "h1">
                                <p class = "perfume_time" style = "padding-top:10px; padding-bottom:5px;">{{product.get_time_display}}</p>
                                <hr class = "h2">
                                <p class = "perfume_note" style = "padding-top:5px; padding-bottom:3px; width:95%;">{{product.get_note_group_display}}</p>
                              </div>
                          </figcaption>
                        </figure>
                      </div>
                      </a>
                    {%endfor%}
                  </div>
                </section>
                <section id="dislike" class="tab-panel">
                  <div class="perfume_list">
                    {%for product in dislike_product_list%}
                    <a href="{%url 'product' product.name%}">
                      <div class = "perfume">
                        <figure class = "perfume_thumb">
                          <img src="{% get_static_prefix %}img/{{product.perfume_img}}.jpg" class="perfume_img">
                          <figcaption class="perfume_caption">
                            <p class = "perfume_brand">[{{product.brand}}]</p>
                            <p class = "perfume_name">{{product.name}}</p>
                              <div class = "perfume_info">
                                <hr class = "h1">
                                <p class = "perfume_time" style = "padding-top:10px; padding-bottom:5px;">{{product.get_time_display}}</p>
                                <hr class = "h2">
                                <p class = "perfume_note" style = "padding-top:5px; padding-bottom:3px; width:95%;">{{product.get_note_group_display}}</p>
                              </div>
                          </figcaption>
                        </figure>
                      </div>
                      </a>
                    {%endfor%}
                  </div>
                </section>
              </div>
              
          
          </div>
          <div class="perfume_comment">
            <p class="post-title">[COMMENT]</p>
              <div class=list-group1>
                {%for comment in comment_list%}
                  <div class = "comm_list">
                    <a href="{%url 'product' comment.name %}" method="POST" class = "a1">
                      
                        <h1 class = "comm_title">{{comment.name}}</h1>
                        <h1 class = "comm_cont">{{comment.content}}</h1>
                        <h1 class = "comm_date">{{comment.pub_date}}</h1>

                    </a>
                  </div>
                {%endfor%}
              </div>
          </div>
        </div>
      </div>
      </div>
      <br>
      <div class="info2">
        <p class="subtitle">COMMUNITY</p1>
          <hr class = "line">
          <div class="posts">
            <div class="post">
              <p class="post-title">[POST]</p>
              <div class="list-group1">
                {%for community in community_list%}
                <div class = "comu_post">
                  <a href="{%url 'community_detail' community.id %}" method="POST" class = "a1">
                      <h1 class = "comu_title">{{community.title}}</h1>
                      <h1 class = "comu_date">{{community.date}}</h1>            
                  </a>
                </div>
                {%endfor%}
              </div>
            </div>
            <div class="comment">
              <p class="post-title">[COMMENT]</p>
              <div class="list-group1">
                {%for com in com_comment%}
                <div class = "comu_comm">
                <a href="{%url 'community_detail' com.post_id %}" method="POST" class = "a1">
                  <h1 class = "comm_cont">{{com.comment_text}}</h1>
                  <h1 class = "comm_date">{{com.created_at}}</h1>
                  
                </a>
                </div>
                {%endfor%}
              </div>
            </div>

          </div>
      </div>
      <br>
      <div class="info4">
        <p class="subtitle">SAVED</p1>
          <hr class = "line">
          <div class="likepost">
            <p class="post-title">[POST]</p>
            <div class="list-group2">
              {%for post in save_post_list%}
              <div class = "comu_post2">
                <a href="{%url 'community_detail' post.id %}" method="POST" class = "a1">
                
                  <h1 class = "comu_title">{{post.title}}</h1>
                  <h1 class = "comu_date">{{post.date}}</h1>         
                
                </a>
              </div>
              {%endfor%}
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

pjgibume/gibumeapp/templates/search.html
{% extends 'base.html' %} {%block content%}

<head>
    {% load static %} {% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    {% endblock %}

</head>

<body>
    <div class="main">
        
        <img src="{% get_static_prefix %}img/logo2.png" class = "logo">
        
        <div class = "search_box">
            <form action ="search" method = "POST">
            {% csrf_token %}
              <div class = "search">
                <input class = "search" type = "text"  name = "search_key" value = "{{search_key}}" placeholder = "search"/>
                <button class = "submit_button" type = "submit" value = "Search">검색</button>
              </div>
            </form>
        </div>

        <div class="search_result">
            {% if not search_list %}
        
            <h1 class = "result">: 검색 결과가 없습니다</h1>

            {% else %}
            {% if search_key %}
            <h1 class="result">: {{search_key}}의 검색결과입니다.</h1>
            {% endif %}
            
            <div class = "value_select" style="overflow-x:hidden; overflow-y:scroll;">
              {% for search_result in search_list %}
                <a href="{%url 'product' search_result.name%}">
                  <div class = "perfume">
                    <figure class = "perfume_thumb">
                      <img src="{% get_static_prefix %}img/{{search_result.perfume_img}}.jpg" class="perfume_img">
                      <figcaption class="perfume_caption">
                        <p class = "perfume_brand">[{{search_result.brand}}]</p>
                        <p class = "perfume_name">{{search_result.name}}</p>
                          <div class = "perfume_info">
                            <hr class = "h1">
                            <p class = "perfume_time" style = "padding-top:10px; padding-bottom:5px;">{{search_result.get_time_display}}</p>
                            <hr class = "h2">
                            <p class = "perfume_note" style = "padding-top:5px; padding-bottom:3px; width:95%;">{{search_result.get_note_group_display}}</p>
                          </div>
                      </figcaption>
                    </figure>
                  </div> 
                </a>
                {% endfor %} {% endif %}
                </div>
            </div>

        </div>
      </div>
 
</body>
{% endblock%}

pjgibume/gibumeapp/templates/test.html
{% extends 'base.html' %} {%block content%} {% load static %}

<head>
    {% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
    <title>TEST</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    {% endblock %}
</head>

<body>
    <div class="homeLandingTop">
        <!-- 테스트 페이지 타이틀 -->
        <div class="main_title">
            <span>나에게 어울리는 향수는?</span>
        </div>
        <!-- 멘트 -->
        <div class="sub_title">
            <span>몇 가지 질문으로 당신에게 가장 어울리는 향수를 추천드려요.
            </span>
        </div>
        <br><br><br>
        <!-- 시작 -->
        <div class="start_buttonWrapper">
            <a href="{% url 'form' %}">
                <div class="buttonItem">시작하기</div>
            </a>
    </div>
    {% endblock%}
</body>